package Modelo;
// Generated 9/05/2016 04:34:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Juegos generated by hbm2java
 */
@Entity
@Table(name="juegos"
    ,schema="public"
)
public class Juegos  implements java.io.Serializable {


     private int idJuego;
     private Usuario usuario;
     private Videojuego videojuego;

    public Juegos() {
    }

    public Juegos(int idJuego, Usuario usuario, Videojuego videojuego) {
       this.idJuego = idJuego;
       this.usuario = usuario;
       this.videojuego = videojuego;
    }
   
     @Id 

    
    @Column(name="id_juego", unique=true, nullable=false)
    public int getIdJuego() {
        return this.idJuego;
    }
    
    public void setIdJuego(int idJuego) {
        this.idJuego = idJuego;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_videojuego", nullable=false)
    public Videojuego getVideojuego() {
        return this.videojuego;
    }
    
    public void setVideojuego(Videojuego videojuego) {
        this.videojuego = videojuego;
    }




}


