package Modelo;
// Generated 17/05/2016 01:23:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Administrador administrador;
     private String usernameUsuario;
     private String passwordUsuario;
     private String nombreUsuario;
     private int tipoUsuario;
     private Set estudiantes = new HashSet(0);
     private Set juegoses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String usernameUsuario, String passwordUsuario, String nombreUsuario, int tipoUsuario) {
        this.idUsuario = idUsuario;
        this.usernameUsuario = usernameUsuario;
        this.passwordUsuario = passwordUsuario;
        this.nombreUsuario = nombreUsuario;
        this.tipoUsuario = tipoUsuario;
    }
    public Usuario(int idUsuario, Administrador administrador, String usernameUsuario, String passwordUsuario, String nombreUsuario, int tipoUsuario, Set estudiantes, Set juegoses) {
       this.idUsuario = idUsuario;
       this.administrador = administrador;
       this.usernameUsuario = usernameUsuario;
       this.passwordUsuario = passwordUsuario;
       this.nombreUsuario = nombreUsuario;
       this.tipoUsuario = tipoUsuario;
       this.estudiantes = estudiantes;
       this.juegoses = juegoses;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_admin")
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }

    
    @Column(name="username_usuario", nullable=false, length=20)
    public String getUsernameUsuario() {
        return this.usernameUsuario;
    }
    
    public void setUsernameUsuario(String usernameUsuario) {
        this.usernameUsuario = usernameUsuario;
    }

    
    @Column(name="password_usuario", nullable=false, length=128)
    public String getPasswordUsuario() {
        return this.passwordUsuario;
    }
    
    public void setPasswordUsuario(String passwordUsuario) {
        this.passwordUsuario = passwordUsuario;
    }

    
    @Column(name="nombre_usuario", nullable=false, length=30)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="tipo_usuario", nullable=false)
    public int getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(int tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getJuegoses() {
        return this.juegoses;
    }
    
    public void setJuegoses(Set juegoses) {
        this.juegoses = juegoses;
    }




}


