package Modelo;
// Generated 9/05/2016 04:34:32 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Videojuego generated by hbm2java
 */
@Entity
@Table(name="videojuego"
    ,schema="public"
)
public class Videojuego  implements java.io.Serializable {


     private int idVideojuego;
     private Administrador administrador;
     private Asignatura asignatura;
     private String nombreJuego;
     private Serializable tamanioJuego;
     private String nombreAutor;
     private String versionJuego;
     private boolean boolPublicar;
     private String descripcion;
     private Set juegoses = new HashSet(0);

    public Videojuego() {
    }

	
    public Videojuego(int idVideojuego, Administrador administrador, Asignatura asignatura, String nombreJuego, Serializable tamanioJuego, String versionJuego, boolean boolPublicar) {
        this.idVideojuego = idVideojuego;
        this.administrador = administrador;
        this.asignatura = asignatura;
        this.nombreJuego = nombreJuego;
        this.tamanioJuego = tamanioJuego;
        this.versionJuego = versionJuego;
        this.boolPublicar = boolPublicar;
    }
    public Videojuego(int idVideojuego, Administrador administrador, Asignatura asignatura, String nombreJuego, Serializable tamanioJuego, String nombreAutor, String versionJuego, boolean boolPublicar, String descripcion, Set juegoses) {
       this.idVideojuego = idVideojuego;
       this.administrador = administrador;
       this.asignatura = asignatura;
       this.nombreJuego = nombreJuego;
       this.tamanioJuego = tamanioJuego;
       this.nombreAutor = nombreAutor;
       this.versionJuego = versionJuego;
       this.boolPublicar = boolPublicar;
       this.descripcion = descripcion;
       this.juegoses = juegoses;
    }
   
     @Id 

    
    @Column(name="id_videojuego", unique=true, nullable=false)
    public int getIdVideojuego() {
        return this.idVideojuego;
    }
    
    public void setIdVideojuego(int idVideojuego) {
        this.idVideojuego = idVideojuego;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_admin", nullable=false)
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_asignatura", nullable=false)
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    
    @Column(name="nombre_juego", nullable=false, length=50)
    public String getNombreJuego() {
        return this.nombreJuego;
    }
    
    public void setNombreJuego(String nombreJuego) {
        this.nombreJuego = nombreJuego;
    }

    
    @Column(name="tamanio_juego", nullable=false)
    public Serializable getTamanioJuego() {
        return this.tamanioJuego;
    }
    
    public void setTamanioJuego(Serializable tamanioJuego) {
        this.tamanioJuego = tamanioJuego;
    }

    
    @Column(name="nombre_autor", length=30)
    public String getNombreAutor() {
        return this.nombreAutor;
    }
    
    public void setNombreAutor(String nombreAutor) {
        this.nombreAutor = nombreAutor;
    }

    
    @Column(name="version_juego", nullable=false, length=10)
    public String getVersionJuego() {
        return this.versionJuego;
    }
    
    public void setVersionJuego(String versionJuego) {
        this.versionJuego = versionJuego;
    }

    
    @Column(name="bool_publicar", nullable=false)
    public boolean isBoolPublicar() {
        return this.boolPublicar;
    }
    
    public void setBoolPublicar(boolean boolPublicar) {
        this.boolPublicar = boolPublicar;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="videojuego")
    public Set getJuegoses() {
        return this.juegoses;
    }
    
    public void setJuegoses(Set juegoses) {
        this.juegoses = juegoses;
    }




}


