INSERT INTO grado (nombre) VALUES ('1er grado'),
('2do grado'),
('3er grado'),
('4to grado'),
('5to grado'),
('6to grado');
INSERT INTO asignatura (nombre, grado) VALUES ('Español 1', 1),
('Matemáticas 1', 1),
('Exploración de la Naturaleza y Sociedad 1', 1), 
('Formación Civica y Ética 1', 1), 
('Educación Artística 1', 1), 
('Español 2', 2),
('Matemáticas 2', 2),
('Exploración de la Naturaleza y Sociedad 2', 2), 
('Formación Civica y Ética 2', 2), 
('Educación Artística 2', 2),
('Español 3', 3),
('Matemáticas 3', 3),
('Ciencias Naturales 1', 3),
('Formación Civica y Ética 3', 3), 
('Educación Artística 3', 3), 
('La Entidad Donde Vivo 1', 3),
('Español 4', 4),
('Matemáticas 4', 4),
('Ciencias Naturales 2', 4), 
('Formación Civica y Ética 4', 4), 
('Educación Artística 4', 4),
('Geografía 1', 4),
('Historia 1', 4),
('Español 5', 5),
('Matemáticas 5', 5),
('Ciencias Naturales 3', 5),
('Geografía 2', 5),
('Formación Civica y Ética 5', 5), 
('Educación Artística 5', 5),
('Historia 2', 5),
('Español 6', 6),
('Matemáticas 6', 6),
('Ciencias Naturales 4', 6),
('Geografía 3', 6),
('Formación Civica y Ética 6', 6), 
('Educación Artística 6', 6), 
('Historia 3', 6);
