package model;
// Generated Jun 3, 2016 5:58:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="id_usuario") 
)
public class Administrador  implements java.io.Serializable {


     private int idAdmin;
     private Usuario usuario;
     private Set juegos = new HashSet(0);

    public Administrador() {
    }

	
    public Administrador(int idAdmin, Usuario usuario) {
        this.idAdmin = idAdmin;
        this.usuario = usuario;
    }
    public Administrador(int idAdmin, Usuario usuario, Set juegos) {
       this.idAdmin = idAdmin;
       this.usuario = usuario;
       this.juegos = juegos;
    }
   
     @Id 

    
    @Column(name="id_admin", unique=true, nullable=false)
    public int getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(int idAdmin) {
        this.idAdmin = idAdmin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", unique=true, nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="administrador")
    public Set getJuegos() {
        return this.juegos;
    }
    
    public void setJuegos(Set juegos) {
        this.juegos = juegos;
    }




}


