package model;
// Generated Jun 3, 2016 5:58:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name="asignatura"
    ,schema="public"
)
public class Asignatura  implements java.io.Serializable {


     private int idAsignatura;
     private Grado grado;
     private String nombre;
     private Set juegos = new HashSet(0);

    public Asignatura() {
    }

	
    public Asignatura(int idAsignatura, Grado grado, String nombre) {
        this.idAsignatura = idAsignatura;
        this.grado = grado;
        this.nombre = nombre;
    }
    public Asignatura(int idAsignatura, Grado grado, String nombre, Set juegos) {
       this.idAsignatura = idAsignatura;
       this.grado = grado;
       this.nombre = nombre;
       this.juegos = juegos;
    }
   
     @Id 

    
    @Column(name="id_asignatura", unique=true, nullable=false)
    public int getIdAsignatura() {
        return this.idAsignatura;
    }
    
    public void setIdAsignatura(int idAsignatura) {
        this.idAsignatura = idAsignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grado", nullable=false)
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asignatura")
    public Set getJuegos() {
        return this.juegos;
    }
    
    public void setJuegos(Set juegos) {
        this.juegos = juegos;
    }




}


