package model;
// Generated Jun 3, 2016 5:58:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Favorito generated by hbm2java
 */
@Entity
@Table(name="favorito"
    ,schema="public"
)
public class Favorito  implements java.io.Serializable {


     private int idFavorito;
     private Estudiante estudiante;
     private Juego juego;

    public Favorito() {
    }

    public Favorito(int idFavorito, Estudiante estudiante, Juego juego) {
       this.idFavorito = idFavorito;
       this.estudiante = estudiante;
       this.juego = juego;
    }
   
     @Id 

    
    @Column(name="id_favorito", unique=true, nullable=false)
    public int getIdFavorito() {
        return this.idFavorito;
    }
    
    public void setIdFavorito(int idFavorito) {
        this.idFavorito = idFavorito;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_estudiante", nullable=false)
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_juego", nullable=false)
    public Juego getJuego() {
        return this.juego;
    }
    
    public void setJuego(Juego juego) {
        this.juego = juego;
    }




}


