package model;
// Generated Jun 3, 2016 5:58:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grado generated by hbm2java
 */
@Entity
@Table(name="grado"
    ,schema="public"
)
public class Grado  implements java.io.Serializable {


     private int idGrado;
     private String nombre;
     private Set asignaturas = new HashSet(0);
     private Set estudiantes = new HashSet(0);

    public Grado() {
    }

	
    public Grado(int idGrado, String nombre) {
        this.idGrado = idGrado;
        this.nombre = nombre;
    }
    public Grado(int idGrado, String nombre, Set asignaturas, Set estudiantes) {
       this.idGrado = idGrado;
       this.nombre = nombre;
       this.asignaturas = asignaturas;
       this.estudiantes = estudiantes;
    }
   
     @Id 

    
    @Column(name="id_grado", unique=true, nullable=false)
    public int getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(int idGrado) {
        this.idGrado = idGrado;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grado")
    public Set getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Set asignaturas) {
        this.asignaturas = asignaturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grado")
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


