package model;
// Generated Jun 3, 2016 5:58:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Imagen generated by hbm2java
 */
@Entity
@Table(name="imagen"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="id_estudiante") 
)
public class Imagen  implements java.io.Serializable {


     private int idImagen;
     private Estudiante estudiante;
     private byte[] imagen;
     private String nombre;

    public Imagen() {
    }

    public Imagen(int idImagen, Estudiante estudiante, byte[] imagen, String nombre) {
       this.idImagen = idImagen;
       this.estudiante = estudiante;
       this.imagen = imagen;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="id_imagen", unique=true, nullable=false)
    public int getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(int idImagen) {
        this.idImagen = idImagen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_estudiante", unique=true, nullable=false)
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    
    @Column(name="imagen", nullable=false)
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }

    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


