package model;
// Generated Jun 3, 2016 5:58:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
    , uniqueConstraints = {@UniqueConstraint(columnNames="correo"), @UniqueConstraint(columnNames="username")} 
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String username;
     private String password;
     private String correo;
     private Date fechaDeRegistro;
     private Set estudiantes = new HashSet(0);
     private Set administradors = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String username, String password, String correo, Date fechaDeRegistro) {
        this.idUsuario = idUsuario;
        this.username = username;
        this.password = password;
        this.correo = correo;
        this.fechaDeRegistro = fechaDeRegistro;
    }
    public Usuario(int idUsuario, String username, String password, String correo, Date fechaDeRegistro, Set estudiantes, Set administradors) {
       this.idUsuario = idUsuario;
       this.username = username;
       this.password = password;
       this.correo = correo;
       this.fechaDeRegistro = fechaDeRegistro;
       this.estudiantes = estudiantes;
       this.administradors = administradors;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="username", unique=true, nullable=false, length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="correo", unique=true, nullable=false, length=20)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_de_registro", nullable=false, length=29)
    public Date getFechaDeRegistro() {
        return this.fechaDeRegistro;
    }
    
    public void setFechaDeRegistro(Date fechaDeRegistro) {
        this.fechaDeRegistro = fechaDeRegistro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }




}


